services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wazum\Sluggi\:
    resource: '../Classes/*'

  Wazum\Sluggi\DataHandler\HandlePageUpdate:
    public: true

  Wazum\Sluggi\DataHandler\HandleExcludeSlugForSubpages:
    public: true
